plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alphamarr.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.alphamarr.app'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '1.1'
    }

    signingConfigs {
        release {
            storeFile file('alphamarr.keystore')
            storePassword 'alphamarr'
            keyAlias 'alphamarr'
            keyPassword 'alphamarr'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
